FROM postgres:13

# Set environment variables
ENV POSTGRES_DB=odoo
ENV POSTGRES_USER=odoo
ENV POSTGRES_PASSWORD=odoo
ENV PGDATA=/var/lib/postgresql/data/pgdata

# Create data directory
RUN mkdir -p /var/lib/postgresql/data

# Expose port
EXPOSE 5432

# Start PostgreSQL
CMD ["postgres"]
